import Foundation
import SwiftUI

struct DistributionZoneView: View {
    @State private var searchText = ""
    @State private var distributionZones: [DistributionZone] = {
        return loadDistributionZones()
    }()
    
    struct UserDefaultsKeys {
         static let selectedZone = "selectedZone"
     }

    var filteredDistributionZones: [DistributionZone] {
         distributionZones.filter { zone in
             searchText.isEmpty || zone.name.localizedStandardContains(searchText)
         }
     }
    
    var body: some View {
        NavigationView {
            VStack {
                SearchBar(text: $searchText)
                List(filteredDistributionZones) { zone in
                    NavigationLink(destination: PlantListView(apiController: APIController(), selectedZone: zone.code)) {
                        Text("\(zone.name)")
                    }.onTapGesture {
                        saveSelectedZone(zone: zone)
                    }
                }
            }
        }
    }
    
    func saveSelectedZone(zone: DistributionZone) {
        print("Saving zone: \(zone.name)") 
        UserDefaults.standard.set(zone.name, forKey: UserDefaultsKeys.selectedZone)
    }
}

// Assuming we have this function to load the distribution zones.
func loadDistributionZones() -> [DistributionZone] {
    // Replace this with your actual data loading logic
    return [
        DistributionZone(code: "1", name: "Europe"),
        DistributionZone(code: "10", name: "Northern Europe"),
        DistributionZone(code: "DEN", name: "Denmark"),
        DistributionZone(code: "FIN", name: "Finland"),
        DistributionZone(code: "FOR", name: "Føroyar"),
        DistributionZone(code: "GRB", name: "Great Britain"),
        DistributionZone(code: "ICE", name: "Iceland"),
        DistributionZone(code: "IRE", name: "Ireland"),
        DistributionZone(code: "IRE-IR", name: "Ireland"),
        DistributionZone(code: "IRE-NI", name: "Northern Ireland"),
        DistributionZone(code: "NOR", name: "Norway"),
        DistributionZone(code: "SVA", name: "Svalbard"),
        DistributionZone(code: "SWE", name: "Sweden"),
        DistributionZone(code: "11", name: "Middle Europe"),
        DistributionZone(code: "AUT", name: "Austria"),
        DistributionZone(code: "AUT-AU", name: "Austria"),
        DistributionZone(code: "AUT-LI", name: "Liechtenstein"),
        DistributionZone(code: "BGM", name: "Belgium"),
        DistributionZone(code: "BGM-LU", name: "Luxembourg"),
        DistributionZone(code: "CZE", name: "Czechoslovakia"),
        DistributionZone(code: "CZE-CZ", name: "Czech Republic"),
        DistributionZone(code: "CZE-SL", name: "Slovakia"),
        DistributionZone(code: "GER", name: "Germany"),
        DistributionZone(code: "HUN", name: "Hungary"),
        DistributionZone(code: "NET", name: "Netherlands"),
        DistributionZone(code: "POL", name: "Poland"),
        DistributionZone(code: "SWI", name: "Switzerland"),
        DistributionZone(code: "12", name: "Southwestern Europe"),
        DistributionZone(code: "BAL", name: "Baleares"),
        DistributionZone(code: "COR", name: "Corse"),
        DistributionZone(code: "FRA", name: "France"),
        DistributionZone(code: "FRA-CI", name: "Channel Is."),
        DistributionZone(code: "FRA-FR", name: "France"),
        DistributionZone(code: "FRA-MO", name: "Monaco"),
        DistributionZone(code: "POR", name: "Portugal"),
        DistributionZone(code: "SAR", name: "Sardegna"),
        DistributionZone(code: "SPA", name: "Spain"),
        DistributionZone(code: "SPA-AN", name: "Andorra"),
        DistributionZone(code: "SPA-GI", name: "Gibraltar"),
        DistributionZone(code: "SPA-SP", name: "Spain"),
        DistributionZone(code: "13", name: "Southeastern Europe"),
        DistributionZone(code: "ALB", name: "Albania"),
        DistributionZone(code: "BUL", name: "Bulgaria"),
        DistributionZone(code: "GRC", name: "Greece"),
        DistributionZone(code: "ITA", name: "Italy"),
        DistributionZone(code: "ITA-IT", name: "Italy"),
        DistributionZone(code: "ITA-SM", name: "San Marino"),
        DistributionZone(code: "ITA-VC", name: "Vatican City"),
        DistributionZone(code: "KRI", name: "Kriti"),
        DistributionZone(code: "ROM", name: "Romania"),
        DistributionZone(code: "SIC", name: "Sicilia"),
        DistributionZone(code: "SIC-MA", name: "Malta"),
        DistributionZone(code: "SIC-SI", name: "Sicilia"),
        DistributionZone(code: "TUE", name: "Turkey-in-Europe"),
        DistributionZone(code: "YUG", name: "Yugoslavia"),
        DistributionZone(code: "YUG-BH", name: "Bosnia- Herzegovina"),
        DistributionZone(code: "YUG-CR", name: "Croatia"),
        DistributionZone(code: "YUG-KO", name: "Kosovo"),
        DistributionZone(code: "YUG-MA", name: "Macedonia"),
        DistributionZone(code: "YUG-MN", name: "Montenegro"),
        DistributionZone(code: "YUG-SE", name: "Serbia"),
        DistributionZone(code: "YUG-SL", name: "Slovenia"),
        DistributionZone(code: "14", name: "Eastern Europe"),
        DistributionZone(code: "BLR", name: "Belarus"),
        DistributionZone(code: "BLT", name: "Baltic States"),
        DistributionZone(code: "BLT-ES", name: "Estonia"),
        DistributionZone(code: "BLT-KA", name: "Kaliningrad"),
        DistributionZone(code: "BLT-LA", name: "Latvia"),
        DistributionZone(code: "BLT-LI", name: "Lithuania"),
        DistributionZone(code: "KRY", name: "Krym"),
        DistributionZone(code: "RUC", name: "Central European Russia"),
        DistributionZone(code: "RUE", name: "East European Russia"),
        DistributionZone(code: "RUN", name: "North European Russia"),
        DistributionZone(code: "RUS", name: "South European Russia"),
        DistributionZone(code: "RUW", name: "Northwest European Russia"),
        DistributionZone(code: "UKR", name: "Ukraine"),
        DistributionZone(code: "UKR-MO", name: "Moldova"),
        DistributionZone(code: "UKR-UK", name: "Ukraine"),
        DistributionZone(code: "2", name: "Africa"),
        DistributionZone(code: "20", name: "Northern Africa"),
        DistributionZone(code: "ALG", name: "Algeria"),
        DistributionZone(code: "EGY", name: "Egypt"),
        DistributionZone(code: "LBY", name: "Libya"),
        DistributionZone(code: "MOR", name: "Morocco"),
        DistributionZone(code: "MOR-MO", name: "Morocco"),
        DistributionZone(code: "MOR-SP", name: "Spanish North African Territories"),
        DistributionZone(code: "TUN", name: "Tunisia"),
        DistributionZone(code: "WSA", name: "Western Sahara"),
        DistributionZone(code: "21", name: "Macaronesia"),
        DistributionZone(code: "AZO", name: "Azores"),
        DistributionZone(code: "CNY", name: "Canary Is."),
        DistributionZone(code: "CVI", name: "Cape Verde"),
        DistributionZone(code: "MDR", name: "Madeira"),
        DistributionZone(code: "SEL", name: "Selvagens"),
        DistributionZone(code: "22", name: "West Tropical Africa"),
        DistributionZone(code: "BEN", name: "Benin"),
        DistributionZone(code: "BKN", name: "Burkina"),
        DistributionZone(code: "GAM", name: "Gambia, The"),
        DistributionZone(code: "GHA", name: "Ghana"),
        DistributionZone(code: "GNB", name: "Guinea-Bissau"),
        DistributionZone(code: "GUI", name: "Guinea"),
        DistributionZone(code: "IVO", name: "Ivory Coast"),
        DistributionZone(code: "LBR", name: "Liberia"),
        DistributionZone(code: "MLI", name: "Mali"),
        DistributionZone(code: "MTN", name: "Mauritania"),
        DistributionZone(code: "NGA", name: "Nigeria"),
        DistributionZone(code: "NGR", name: "Niger"),
        DistributionZone(code: "SEN", name: "Senegal"),
        DistributionZone(code: "SIE", name: "Sierra Leone"),
        DistributionZone(code: "TOG", name: "Togo"),
        DistributionZone(code: "23", name: "West-Central Tropical Africa"),
        DistributionZone(code: "BUR", name: "Burundi"),
        DistributionZone(code: "CAB", name: "Cabinda"),
        DistributionZone(code: "CAF", name: "Central African Republic"),
        DistributionZone(code: "CMN", name: "Cameroon"),
        DistributionZone(code: "CON", name: "Congo"),
        DistributionZone(code: "EQG", name: "Equatorial Guinea"),
        DistributionZone(code: "GAB", name: "Gabon"),
        DistributionZone(code: "GGI", name: "Gulf of Guinea Is."),
        DistributionZone(code: "GGI-AN", name: "Annobón"),
        DistributionZone(code: "GGI-BI", name: "Bioko"),
        DistributionZone(code: "GGI-PR", name: "Príncipe"),
        DistributionZone(code: "GGI-ST", name: "São Tomé"),
        DistributionZone(code: "RWA", name: "Rwanda"),
        DistributionZone(code: "ZAI", name: "Zaire"),
        DistributionZone(code: "24", name: "Northeast Tropical Africa"),
        DistributionZone(code: "CHA", name: "Chad"),
        DistributionZone(code: "DJI", name: "Djibouti"),
        DistributionZone(code: "ERI", name: "Eritrea"),
        DistributionZone(code: "ETH", name: "Ethiopia"),
        DistributionZone(code: "SOC", name: "Socotra"),
        DistributionZone(code: "SOM", name: "Somalia"),
        DistributionZone(code: "SUD", name: "Sudan"),
        DistributionZone(code: "25", name: "East Tropical Africa"),
        DistributionZone(code: "KEN", name: "Kenya"),
        DistributionZone(code: "TAN", name: "Tanzania"),
        DistributionZone(code: "UGA", name: "Uganda"),
        DistributionZone(code: "26", name: "South Tropical Africa"),
        DistributionZone(code: "ANG", name: "Angola"),
        DistributionZone(code: "MLW", name: "Malawi"),
        DistributionZone(code: "MOZ", name: "Mozambique"),
        DistributionZone(code: "ZAM", name: "Zambia"),
        DistributionZone(code: "ZIM", name: "Zimbabwe"),
        DistributionZone(code: "27", name: "Southern Africa"),
        DistributionZone(code: "BOT", name: "Botswana"),
        DistributionZone(code: "CPP", name: "Cape Provinces"),
        DistributionZone(code: "CPP-EC", name: "Eastern Cape Province"),
        DistributionZone(code: "CPP-NC", name: "Northern Cape Province"),
        DistributionZone(code: "CPP-WC", name: "Western Cape Province"),
        DistributionZone(code: "CPV", name: "Caprivi Strip"),
        DistributionZone(code: "LES", name: "Lesotho"),
        DistributionZone(code: "NAM", name: "Namibia"),
        DistributionZone(code: "NAT", name: "KwaZulu-Natal"),
        DistributionZone(code: "OFS", name: "Free State"),
        DistributionZone(code: "SWZ", name: "Swaziland"),
        DistributionZone(code: "TVL", name: "Northern Provinces"),
        DistributionZone(code: "TVL-GA", name: "Gauteng"),
        DistributionZone(code: "TVL-MP", name: "Mpumalanga"),
        DistributionZone(code: "TVL-NP", name: "Northern Province"),
        DistributionZone(code: "TVL-NW", name: "North-West Province"),
        DistributionZone(code: "28", name: "Middle Atlantic Ocean"),
        DistributionZone(code: "ASC", name: "Ascension"),
        DistributionZone(code: "STH", name: "St.Helena"),
        DistributionZone(code: "29", name: "Western Indian Ocean"),
        DistributionZone(code: "ALD", name: "Aldabra"),
        DistributionZone(code: "CGS", name: "Chagos Archipelago"),
        DistributionZone(code: "COM", name: "Comoros"),
        DistributionZone(code: "COM-CO", name: "Comoros"),
        DistributionZone(code: "COM-MA", name: "Mayotte"),
        DistributionZone(code: "MAU", name: "Mauritius"),
        DistributionZone(code: "MCI", name: "Mozambique Channel Is."),
        DistributionZone(code: "MDG", name: "Madagascar"),
        DistributionZone(code: "REU", name: "Réunion"),
        DistributionZone(code: "ROD", name: "Rodrigues"),
        DistributionZone(code: "SEY", name: "Seychelles"),
        DistributionZone(code: "3", name: "Asia-Temperate"),
        DistributionZone(code: "30", name: "Siberia"),
        DistributionZone(code: "ALT", name: "Altay"),
        DistributionZone(code: "BRY", name: "Buryatiya"),
        DistributionZone(code: "CTA", name: "Chita"),
        DistributionZone(code: "IRK", name: "Irkutsk"),
        DistributionZone(code: "KRA", name: "Krasnoyarsk"),
        DistributionZone(code: "TVA", name: "Tuva"),
        DistributionZone(code: "WSB", name: "West Siberia"),
        DistributionZone(code: "YAK", name: "Yakutskiya"),
        DistributionZone(code: "31", name: "Russian Far East"),
        DistributionZone(code: "AMU", name: "Amur"),
        DistributionZone(code: "KAM", name: "Kamchatka"),
        DistributionZone(code: "KHA", name: "Khabarovsk"),
        DistributionZone(code: "KUR", name: "Kuril Is."),
        DistributionZone(code: "MAG", name: "Magadan"),
        DistributionZone(code: "PRM", name: "Primorye"),
        DistributionZone(code: "SAK", name: "Sakhalin"),
        DistributionZone(code: "32", name: "Middle Asia"),
        DistributionZone(code: "KAZ", name: "Kazakhstan"),
        DistributionZone(code: "KGZ", name: "Kirgizistan"),
        DistributionZone(code: "TKM", name: "Turkmenistan"),
        DistributionZone(code: "TZK", name: "Tadzhikistan"),
        DistributionZone(code: "UZB", name: "Uzbekistan"),
        DistributionZone(code: "33", name: "Caucasus"),
        DistributionZone(code: "NCS", name: "North Caucasus"),
        DistributionZone(code: "NCS-CH", name: "Chechnya"),
        DistributionZone(code: "NCS-DA", name: "Dagestan"),
        DistributionZone(code: "NCS-IN", name: "Ingushetiya"),
        DistributionZone(code: "NCS-KB", name: "Kabardino-Balkariya"),
        DistributionZone(code: "NCS-KC", name: "Karacheyevo-Cherkessiya"),
        DistributionZone(code: "NCS-KR", name: "Krasnodar"),
        DistributionZone(code: "NCS-SO", name: "Severo-Osetiya"),
        DistributionZone(code: "NCS-ST", name: "Stavropol"),
        DistributionZone(code: "TCS", name: "Transcaucasus"),
        DistributionZone(code: "TCS-AB", name: "Abkhaziya"),
        DistributionZone(code: "TCS-AD", name: "Adzhariya"),
        DistributionZone(code: "TCS-AR", name: "Armenia"),
        DistributionZone(code: "TCS-AZ", name: "Azerbaijan"),
        DistributionZone(code: "TCS-GR", name: "Gruziya"),
        DistributionZone(code: "TCS-NA", name: "Nakhichevan"),
        DistributionZone(code: "TCS-NK", name: "Nagorno Karabakh"),
        DistributionZone(code: "34", name: "Western Asia"),
        DistributionZone(code: "AFG", name: "Afghanistan"),
        DistributionZone(code: "CYP", name: "Cyprus"),
        DistributionZone(code: "EAI", name: "East Aegean Is."),
        DistributionZone(code: "IRN", name: "Iran"),
        DistributionZone(code: "IRQ", name: "Iraq"),
        DistributionZone(code: "LBS", name: "Lebanon-Syria"),
        DistributionZone(code: "LBS-LB", name: "Lebanon"),
        DistributionZone(code: "LBS-SY", name: "Syria"),
        DistributionZone(code: "PAL", name: "Palestine"),
        DistributionZone(code: "PAL-JO", name: "Jordan"),
        DistributionZone(code: "PAL-IS", name: "Israel"),
        DistributionZone(code: "SIN", name: "Sinai"),
        DistributionZone(code: "TUR", name: "Turkey"),
        DistributionZone(code: "35", name: "Arabian Peninsula"),
        DistributionZone(code: "GST", name: "Gulf States"),
        DistributionZone(code: "GST-BA", name: "Bahrain"),
        DistributionZone(code: "GST-QA", name: "Qatar"),
        DistributionZone(code: "GST-UA", name: "United Arab Emirates"),
        DistributionZone(code: "KUW", name: "Kuwait"),
        DistributionZone(code: "OMA", name: "Oman"),
        DistributionZone(code: "SAU", name: "Saudi Arabia"),
        DistributionZone(code: "YEM", name: "Yemen"),
        DistributionZone(code: "YEM-NY", name: "North Yemen"),
        DistributionZone(code: "YEM-SY", name: "South Yemen"),
        DistributionZone(code: "36", name: "China"),
        DistributionZone(code: "CHC", name: "China South-Central"),
        DistributionZone(code: "CHC-CQ", name: "Chongqing"),
        DistributionZone(code: "CHC-GZ", name: "Guizhou"),
        DistributionZone(code: "CHC-HU", name: "Hubei"),
        DistributionZone(code: "CHC-SC", name: "Sichuan"),
        DistributionZone(code: "CHC-YN", name: "Yunnan"),
        DistributionZone(code: "CHH", name: "Hainan"),
        DistributionZone(code: "CHI", name: "Inner Mongolia"),
        DistributionZone(code: "CHI-NM", name: "Nei Mongol"),
        DistributionZone(code: "CHI-NX", name: "Ningxia"),
        DistributionZone(code: "CHM", name: "Manchuria"),
        DistributionZone(code: "CHM-HJ", name: "Heilongjiang"),
        DistributionZone(code: "CHM-JL", name: "Jilin"),
        DistributionZone(code: "CHM-LN", name: "Liaoning"),
        DistributionZone(code: "CHN", name: "China North-Central"),
        DistributionZone(code: "CHN-BJ", name: "Beijing"),
        DistributionZone(code: "CHN-GS", name: "Gansu"),
        DistributionZone(code: "CHN-HB", name: "Hebei"),
        DistributionZone(code: "CHN-SA", name: "Shaanxi"),
        DistributionZone(code: "CHN-SD", name: "Shandong"),
        DistributionZone(code: "CHN-SX", name: "Shanxi"),
        DistributionZone(code: "CHN-TJ", name: "Tianjin"),
        DistributionZone(code: "CHQ", name: "Qinghai"),
        DistributionZone(code: "CHS", name: "China Southeast"),
        DistributionZone(code: "CHS-AH", name: "Anhui"),
        DistributionZone(code: "CHS-FJ", name: "Fujian"),
        DistributionZone(code: "CHS-GD", name: "Guangdong"),
        DistributionZone(code: "CHS-GX", name: "Guangxi"),
        DistributionZone(code: "CHS-HE", name: "Henan"),
        DistributionZone(code: "CHS-HK", name: "Hong Kong"),
        DistributionZone(code: "CHS-HN", name: "Hunan"),
        DistributionZone(code: "CHS-JS", name: "Jiangsu"),
        DistributionZone(code: "CHS-JX", name: "Jiangxi"),
        DistributionZone(code: "CHS-KI", name: "Kin-Men"),
        DistributionZone(code: "CHS-MA", name: "Macau"),
        DistributionZone(code: "CHS-MP", name: "Ma-tsu-Pai-chuan"),
        DistributionZone(code: "CHS-SH", name: "Shanghai"),
        DistributionZone(code: "CHS-ZJ", name: "Zhejiang"),
        DistributionZone(code: "CHT", name: "Tibet"),
        DistributionZone(code: "CHX", name: "Xinjiang"),
        DistributionZone(code: "37", name: "Mongolia"),
        DistributionZone(code: "MON", name: "Mongolia"),
        DistributionZone(code: "38", name: "Eastern Asia"),
        DistributionZone(code: "JAP", name: "Japan"),
        DistributionZone(code: "JAP-HK", name: "Hokkaido"),
        DistributionZone(code: "JAP-HN", name: "Honshu"),
        DistributionZone(code: "JAP-KY", name: "Kyushu"),
        DistributionZone(code: "JAP-SH", name: "Shikoku"),
        DistributionZone(code: "KOR", name: "Korea"),
        DistributionZone(code: "KOR-NK", name: "North Korea"),
        DistributionZone(code: "KOR-SK", name: "South Korea"),
        DistributionZone(code: "KZN", name: "Kazan-retto"),
        DistributionZone(code: "NNS", name: "Nansei-shoto"),
        DistributionZone(code: "OGA", name: "Ogasawara-shoto"),
        DistributionZone(code: "TAI", name: "Taiwan"),
        DistributionZone(code: "4", name: "Asia-Tropical"),
        DistributionZone(code: "40", name: "Indian Subcontinent"),
        DistributionZone(code: "ASS", name: "Assam"),
        DistributionZone(code: "ASS-AS", name: "Assam"),
        DistributionZone(code: "ASS-MA", name: "Manipur"),
        DistributionZone(code: "ASS-ME", name: "Meghalaya"),
        DistributionZone(code: "ASS-MI", name: "Mizoram"),
        DistributionZone(code: "ASS-NA", name: "Nagaland"),
        DistributionZone(code: "ASS-TR", name: "Tripura"),
        DistributionZone(code: "BAN", name: "Bangladesh"),
        DistributionZone(code: "EHM", name: "East Himalaya"),
        DistributionZone(code: "EHM-AP", name: "Arunachal Pradesh"),
        DistributionZone(code: "EHM-BH", name: "Bhutan"),
        DistributionZone(code: "EHM-DJ", name: "Darjiling"),
        DistributionZone(code: "EHM-SI", name: "Sikkim"),
        DistributionZone(code: "IND", name: "India"),
        DistributionZone(code: "IND-AP", name: "Andhra Pradesh"),
        DistributionZone(code: "IND-BI", name: "Bihar"),
        DistributionZone(code: "IND-CH", name: "Chandigarh"),
        DistributionZone(code: "IND-CT", name: "Chhattisgarh"),
        DistributionZone(code: "IND-DD", name: "Dadra-Nagar-Haveli"),
        DistributionZone(code: "IND-DE", name: "Delhi"),
        DistributionZone(code: "IND-DI", name: "Diu"),
        DistributionZone(code: "IND-DM", name: "Daman"),
        DistributionZone(code: "IND-GO", name: "Goa"),
        DistributionZone(code: "IND-GU", name: "Gujarat"),
        DistributionZone(code: "IND-HA", name: "Haryana"),
        DistributionZone(code: "IND-JK", name: "Jharkhand"),
        DistributionZone(code: "IND-KE", name: "Kerala"),
        DistributionZone(code: "IND-KL", name: "Karaikal"),
        DistributionZone(code: "IND-KT", name: "Karnataka"),
        DistributionZone(code: "IND-MH", name: "Mahe"),
        DistributionZone(code: "IND-MP", name: "Madhya Pradesh"),
        DistributionZone(code: "IND-MR", name: "Maharashtra"),
        DistributionZone(code: "IND-OR", name: "Orissa"),
        DistributionZone(code: "IND-PO", name: "Pondicherry"),
        DistributionZone(code: "IND-PU", name: "Punjab"),
        DistributionZone(code: "IND-RA", name: "Rajasthan"),
        DistributionZone(code: "IND-TN", name: "Tamil Nadu"),
        DistributionZone(code: "IND-UP", name: "Uttar Pradesh"),
        DistributionZone(code: "IND-WB", name: "West Bengal"),
        DistributionZone(code: "IND-YA", name: "Yanam"),
        DistributionZone(code: "LDV", name: "Laccadive Is."),
        DistributionZone(code: "MDV", name: "Maldives"),
        DistributionZone(code: "NEP", name: "Nepal"),
        DistributionZone(code: "PAK", name: "Pakistan"),
        DistributionZone(code: "SRL", name: "Sri Lanka"),
        DistributionZone(code: "WHM", name: "West Himalaya"),
        DistributionZone(code: "WHM-HP", name: "Himachal Pradesh"),
        DistributionZone(code: "WHM-JK", name: "Jammu-Kashmir"),
        DistributionZone(code: "WHM-UT", name: "Uttaranchal"),
        DistributionZone(code: "41", name: "Indo-China"),
        DistributionZone(code: "AND", name: "Andaman Is."),
        DistributionZone(code: "AND-AN", name: "Andaman Is."),
        DistributionZone(code: "AND-CO", name: "Coco Is."),
        DistributionZone(code: "CBD", name: "Cambodia"),
        DistributionZone(code: "LAO", name: "Laos"),
        DistributionZone(code: "MYA", name: "Myanmar"),
        DistributionZone(code: "NCB", name: "Nicobar Is."),
        DistributionZone(code: "SCS", name: "South China Sea"),
        DistributionZone(code: "SCS-PI", name: "Paracel Is."),
        DistributionZone(code: "SCS-SI", name: "Spratly Is."),
        DistributionZone(code: "THA", name: "Thailand"),
        DistributionZone(code: "VIE", name: "Vietnam"),
        DistributionZone(code: "42", name: "Malesia"),
        DistributionZone(code: "BOR", name: "Borneo"),
        DistributionZone(code: "BOR-BR", name: "Brunei"),
        DistributionZone(code: "BOR-KA", name: "Kalimantan"),
        DistributionZone(code: "BOR-SB", name: "Sabah"),
        DistributionZone(code: "BOR-SR", name: "Sarawak"),
        DistributionZone(code: "CKI", name: "Cocos (Keeling) Is."),
        DistributionZone(code: "JAW", name: "Jawa"),
        DistributionZone(code: "LSI", name: "Lesser Sunda Is."),
        DistributionZone(code: "LSI-BA", name: "Bali"),
        DistributionZone(code: "LSI-ET", name: "East Timor"),
        DistributionZone(code: "LSI-LS", name: "Lesser Sunda Is."),
        DistributionZone(code: "MLY", name: "Malaya"),
        DistributionZone(code: "MLY-PM", name: "Peninsular Malaysia"),
        DistributionZone(code: "MLY-SI", name: "Singapore"),
        DistributionZone(code: "MOL", name: "Maluku"),
        DistributionZone(code: "PHI", name: "Philippines"),
        DistributionZone(code: "SUL", name: "Sulawesi"),
        DistributionZone(code: "SUM", name: "Sumatera"),
        DistributionZone(code: "XMS", name: "Christmas I."),
        DistributionZone(code: "43", name: "Papuasia"),
        DistributionZone(code: "BIS", name: "Bismarck Archipelago"),
        DistributionZone(code: "NWG", name: "New Guinea"),
        DistributionZone(code: "NWG-PN", name: "Papua New Guinea"),
        DistributionZone(code: "NWG-IJ", name: "Irian Jaya"),
        DistributionZone(code: "SOL", name: "Solomon Is."),
        DistributionZone(code: "SOL-NO", name: "North Solomons"),
        DistributionZone(code: "SOL-SO", name: "South Solomons"),
        DistributionZone(code: "5", name: "Australasia"),
        DistributionZone(code: "50", name: "Australia"),
        DistributionZone(code: "NFK", name: "Norfolk Is."),
        DistributionZone(code: "NFK-LH", name: "Lord Howe I."),
        DistributionZone(code: "NFK-NI", name: "Norfolk I."),
        DistributionZone(code: "NSW", name: "New South Wales"),
        DistributionZone(code: "NSW-CT", name: "Australian Capital Territory"),
        DistributionZone(code: "NSW-NS", name: "New South Wales"),
        DistributionZone(code: "NTA", name: "Northern Territory"),
        DistributionZone(code: "QLD", name: "Queensland"),
        DistributionZone(code: "QLD-CS", name: "Coral Sea Is. Territory"),
        DistributionZone(code: "QLD-QU", name: "Queensland"),
        DistributionZone(code: "SOA", name: "South Australia"),
        DistributionZone(code: "TAS", name: "Tasmania"),
        DistributionZone(code: "VIC", name: "Victoria"),
        DistributionZone(code: "WAU", name: "Western Australia"),
        DistributionZone(code: "WAU-AC", name: "Ashmore-Cartier Is."),
        DistributionZone(code: "WAU-WA", name: "Western Australia"),
        DistributionZone(code: "51", name: "New Zealand"),
        DistributionZone(code: "ATP", name: "Antipodean Is."),
        DistributionZone(code: "CTM", name: "Chatham Is."),
        DistributionZone(code: "KER", name: "Kermadec Is."),
        DistributionZone(code: "NZN", name: "New Zealand North"),
        DistributionZone(code: "NZS", name: "New Zealand South"),
        DistributionZone(code: "6", name: "Pacific"),
        DistributionZone(code: "60", name: "Southwestern Pacific"),
        DistributionZone(code: "FIJ", name: "Fiji"),
        DistributionZone(code: "GIL", name: "Gilbert Is."),
        DistributionZone(code: "HBI", name: "Howland-Baker Is."),
        DistributionZone(code: "NRU", name: "Nauru"),
        DistributionZone(code: "NUE", name: "Niue"),
        DistributionZone(code: "NWC", name: "New Caledonia"),
        DistributionZone(code: "PHX", name: "Phoenix Is."),
        DistributionZone(code: "SAM", name: "Samoa"),
        DistributionZone(code: "SAM-AS", name: "American Samoa"),
        DistributionZone(code: "SAM-WS", name: "Samoa"),
        DistributionZone(code: "SCZ", name: "Santa Cruz Is."),
        DistributionZone(code: "TOK", name: "Tokelau-Manihiki"),
        DistributionZone(code: "TOK-MA", name: "Manihiki Is."),
        DistributionZone(code: "TOK-SW", name: "Swains I."),
        DistributionZone(code: "TOK-TO", name: "Tokelau"),
        DistributionZone(code: "TON", name: "Tonga"),
        DistributionZone(code: "TUV", name: "Tuvalu"),
        DistributionZone(code: "VAN", name: "Vanuatu"),
        DistributionZone(code: "WAL", name: "Wallis-Futuna Is."),
        DistributionZone(code: "61", name: "South-Central Pacific"),
        DistributionZone(code: "COO", name: "Cook Is."),
        DistributionZone(code: "EAS", name: "Easter Is."),
        DistributionZone(code: "LIN", name: "Line Is."),
        DistributionZone(code: "LIN-KI", name: "Kiribati Line Is."),
        DistributionZone(code: "LIN-US", name: "U.S. Line Is."),
        DistributionZone(code: "MRQ", name: "Marquesas"),
        DistributionZone(code: "PIT", name: "Pitcairn Is."),
        DistributionZone(code: "SCI", name: "Society Is."),
        DistributionZone(code: "TUA", name: "Tuamotu"),
        DistributionZone(code: "TUB", name: "Tubuai Is."),
        DistributionZone(code: "62", name: "Northwestern Pacific"),
        DistributionZone(code: "CRL", name: "Caroline Is."),
        DistributionZone(code: "CRL-MF", name: "Micronesia Federated States"),
        DistributionZone(code: "CRL-PA", name: "Palau"),
        DistributionZone(code: "MCS", name: "Marcus I."),
        DistributionZone(code: "MRN", name: "Marianas"),
        DistributionZone(code: "MRN-GU", name: "Guam"),
        DistributionZone(code: "MRN-NM", name: "Northern Marianas"),
        DistributionZone(code: "MRS", name: "Marshall Is."),
        DistributionZone(code: "WAK", name: "Wake I."),
        DistributionZone(code: "63", name: "North-Central Pacific"),
        DistributionZone(code: "HAW", name: "Hawaii"),
        DistributionZone(code: "HAW-HI", name: "Hawaiian Is."),
        DistributionZone(code: "HAW-JI", name: "Johnston I."),
        DistributionZone(code: "HAW-MI", name: "Midway Is."),
        DistributionZone(code: "7", name: "Northern America"),
        DistributionZone(code: "70", name: "Subarctic America"),
        DistributionZone(code: "ALU", name: "Aleutian Is."),
        DistributionZone(code: "ASK", name: "Alaska"),
        DistributionZone(code: "GNL", name: "Greenland"),
        DistributionZone(code: "NUN", name: "Nunavut"),
        DistributionZone(code: "NWT", name: "Northwest Territories"),
        DistributionZone(code: "YUK", name: "Yukon"),
        DistributionZone(code: "71", name: "Western Canada"),
        DistributionZone(code: "ABT", name: "Alberta"),
        DistributionZone(code: "BRC", name: "British Columbia"),
        DistributionZone(code: "MAN", name: "Manitoba"),
        DistributionZone(code: "SAS", name: "Saskatchewan"),
        DistributionZone(code: "72", name: "Eastern Canada"),
        DistributionZone(code: "LAB", name: "Labrador"),
        DistributionZone(code: "NBR", name: "New Brunswick"),
        DistributionZone(code: "NFL", name: "Newfoundland"),
        DistributionZone(code: "NFL-NE", name: "Newfoundland"),
        DistributionZone(code: "NFL-SP", name: "St. Pierre-Miquelon"),
        DistributionZone(code: "NSC", name: "Nova Scotia"),
        DistributionZone(code: "ONT", name: "Ontario"),
        DistributionZone(code: "PEI", name: "Prince Edward I."),
        DistributionZone(code: "QUE", name: "Québec"),
        DistributionZone(code: "73", name: "Northwestern U.S.A."),
        DistributionZone(code: "COL", name: "Colorado"),
        DistributionZone(code: "IDA", name: "Idaho"),
        DistributionZone(code: "MNT", name: "Montana"),
        DistributionZone(code: "ORE", name: "Oregon"),
        DistributionZone(code: "WAS", name: "Washington"),
        DistributionZone(code: "WYO", name: "Wyoming"),
        DistributionZone(code: "74", name: "North-Central U.S.A."),
        DistributionZone(code: "ILL", name: "Illinois"),
        DistributionZone(code: "IOW", name: "Iowa"),
        DistributionZone(code: "KAN", name: "Kansas"),
        DistributionZone(code: "MIN", name: "Minnesota"),
        DistributionZone(code: "MSO", name: "Missouri"),
        DistributionZone(code: "NDA", name: "North Dakota"),
        DistributionZone(code: "NEB", name: "Nebraska"),
        DistributionZone(code: "OKL", name: "Oklahoma"),
        DistributionZone(code: "SDA", name: "South Dakota"),
        DistributionZone(code: "WIS", name: "Wisconsin"),
        DistributionZone(code: "75", name: "Northeastern U.S.A."),
        DistributionZone(code: "CNT", name: "Connecticut"),
        DistributionZone(code: "INI", name: "Indiana"),
        DistributionZone(code: "MAI", name: "Maine"),
        DistributionZone(code: "MAS", name: "Massachusetts"),
        DistributionZone(code: "MIC", name: "Michigan"),
        DistributionZone(code: "NWH", name: "New Hampshire"),
        DistributionZone(code: "NWJ", name: "New Jersey"),
        DistributionZone(code: "NWY", name: "New York"),
        DistributionZone(code: "OHI", name: "Ohio"),
        DistributionZone(code: "PEN", name: "Pennsylvania"),
        DistributionZone(code: "RHO", name: "Rhode I."),
        DistributionZone(code: "VER", name: "Vermont"),
        DistributionZone(code: "WVA", name: "West Virginia"),
        DistributionZone(code: "76", name: "Southwestern U.S.A."),
        DistributionZone(code: "ARI", name: "Arizona"),
        DistributionZone(code: "CAL", name: "California"),
        DistributionZone(code: "NEV", name: "Nevada"),
        DistributionZone(code: "UTA", name: "Utah"),
        DistributionZone(code: "77", name: "South-Central U.S.A."),
        DistributionZone(code: "NWM", name: "New Mexico"),
        DistributionZone(code: "TEX", name: "Texas"),
        DistributionZone(code: "78", name: "Southeastern U.S.A."),
        DistributionZone(code: "ALA", name: "Alabama"),
        DistributionZone(code: "ARK", name: "Arkansas"),
        DistributionZone(code: "DEL", name: "Delaware"),
        DistributionZone(code: "FLA", name: "Florida"),
        DistributionZone(code: "GEO", name: "Georgia"),
        DistributionZone(code: "KTY", name: "Kentucky"),
        DistributionZone(code: "LOU", name: "Louisiana"),
        DistributionZone(code: "MRY", name: "Maryland"),
        DistributionZone(code: "MSI", name: "Mississippi"),
        DistributionZone(code: "NCA", name: "North Carolina"),
        DistributionZone(code: "SCA", name: "South Carolina"),
        DistributionZone(code: "TEN", name: "Tennessee"),
        DistributionZone(code: "VRG", name: "Virginia"),
        DistributionZone(code: "WDC", name: "District of Columbia"),
        DistributionZone(code: "79", name: "Mexico"),
        DistributionZone(code: "MXC", name: "Mexico Central"),
        DistributionZone(code: "MXC-DF", name: "Mexico Distrito Federal"),
        DistributionZone(code: "MXC-ME", name: "Mexico State"),
        DistributionZone(code: "MXC-MO", name: "Morelos"),
        DistributionZone(code: "MXC-PU", name: "Puebla"),
        DistributionZone(code: "MXC-TL", name: "Tlaxcala"),
        DistributionZone(code: "MXE", name: "Mexico Northeast"),
        DistributionZone(code: "MXE-AG", name: "Aguascalientes"),
        DistributionZone(code: "MXE-CO", name: "Coahuila"),
        DistributionZone(code: "MXE-CU", name: "Chihuahua"),
        DistributionZone(code: "MXE-DU", name: "Durango"),
        DistributionZone(code: "MXE-GU", name: "Guanajuato"),
        DistributionZone(code: "MXE-HI", name: "Hidalgo"),
        DistributionZone(code: "MXE-NL", name: "Nuevo León"),
        DistributionZone(code: "MXE-QU", name: "Querétaro"),
        DistributionZone(code: "MXE-SL", name: "San Luis Potosí"),
        DistributionZone(code: "MXE-TA", name: "Tamaulipas"),
        DistributionZone(code: "MXE-ZA", name: "Zacatecas"),
        DistributionZone(code: "MXG", name: "Mexico Gulf"),
        DistributionZone(code: "MXG-VC", name: "Veracruz"),
        DistributionZone(code: "MXI", name: "Mexican Pacific Is."),
        DistributionZone(code: "MXI-GU", name: "Guadalupe I."),
        DistributionZone(code: "MXI-RA", name: "Rocas Alijos"),
        DistributionZone(code: "MXI-RG", name: "Revillagigedo Is."),
        DistributionZone(code: "MXN", name: "Mexico Northwest"),
        DistributionZone(code: "MXN-BC", name: "Baja California"),
        DistributionZone(code: "MXN-BS", name: "Baja California Sur"),
        DistributionZone(code: "MXN-SI", name: "Sinaloa"),
        DistributionZone(code: "MXN-SO", name: "Sonora"),
        DistributionZone(code: "MXS", name: "Mexico Southwest"),
        DistributionZone(code: "MXS-CL", name: "Colima"),
        DistributionZone(code: "MXS-GR", name: "Guerrero"),
        DistributionZone(code: "MXS-JA", name: "Jalisco"),
        DistributionZone(code: "MXS-MI", name: "Michoacan"),
        DistributionZone(code: "MXS-NA", name: "Nayarit"),
        DistributionZone(code: "MXS-OA", name: "Oaxaca"),
        DistributionZone(code: "MXT", name: "Mexico Southeast"),
        DistributionZone(code: "MXT-CA", name: "Campeche"),
        DistributionZone(code: "MXT-CI", name: "Chiapas"),
        DistributionZone(code: "MXT-QR", name: "Quintana Roo"),
        DistributionZone(code: "MXT-TB", name: "Tabasco"),
        DistributionZone(code: "MXT-YU", name: "Yucatán"),
        DistributionZone(code: "8", name: "Southern America"),
        DistributionZone(code: "80", name: "Central America"),
        DistributionZone(code: "BLZ", name: "Belize"),
        DistributionZone(code: "COS", name: "Costa Rica"),
        DistributionZone(code: "CPI", name: "Central American Pacific Is."),
        DistributionZone(code: "CPI-CL", name: "Clipperton I."),
        DistributionZone(code: "CPI-CO", name: "Cocos I."),
        DistributionZone(code: "CPI-MA", name: "Malpelo I."),
        DistributionZone(code: "ELS", name: "El Salvador"),
        DistributionZone(code: "GUA", name: "Guatemala"),
        DistributionZone(code: "HON", name: "Honduras"),
        DistributionZone(code: "NIC", name: "Nicaragua"),
        DistributionZone(code: "PAN", name: "Panama"),
        DistributionZone(code: "81", name: "Caribbean"),
        DistributionZone(code: "ARU", name: "Aruba"),
        DistributionZone(code: "BAH", name: "Bahamas"),
        DistributionZone(code: "BER", name: "Bermuda"),
        DistributionZone(code: "CAY", name: "Cayman Is."),
        DistributionZone(code: "CUB", name: "Cuba"),
        DistributionZone(code: "DOM", name: "Dominican Republic"),
        DistributionZone(code: "HAI", name: "Haiti"),
        DistributionZone(code: "HAI-HA", name: "Haiti"),
        DistributionZone(code: "HAI-NI", name: "Navassa I."),
        DistributionZone(code: "JAM", name: "Jamaica"),
        DistributionZone(code: "LEE", name: "Leeward Is."),
        DistributionZone(code: "LEE-AB", name: "Antigua-Barbuda"),
        DistributionZone(code: "LEE-AG", name: "Anguilla"),
        DistributionZone(code: "LEE-AV", name: "Aves I."),
        DistributionZone(code: "LEE-BV", name: "British Virgin Is."),
        DistributionZone(code: "LEE-GU", name: "Guadeloupe"),
        DistributionZone(code: "LEE-MO", name: "Montserrat"),
        DistributionZone(code: "LEE-NL", name: "Netherlands Leeward Is."),
        DistributionZone(code: "LEE-SK", name: "St. Kitts-Nevis"),
        DistributionZone(code: "LEE-SM", name: "St. Martin-St. Barthelemy"),
        DistributionZone(code: "LEE-VI", name: "Virgin Is."),
        DistributionZone(code: "NLA", name: "Netherlands Antilles"),
        DistributionZone(code: "NLA-BO", name: "Bonaire"),
        DistributionZone(code: "NLA-CU", name: "Curaçao"),
        DistributionZone(code: "PUE", name: "Puerto Rico"),
        DistributionZone(code: "SWC", name: "Southwest Caribbean"),
        DistributionZone(code: "SWC-CC", name: "Colombian Caribbean Is."),
        DistributionZone(code: "SWC-HC", name: "Honduran Caribbean Is."),
        DistributionZone(code: "SWC-NC", name: "Nicaraguan Caribbean Is."),
        DistributionZone(code: "TCI", name: "Turks-Caicos Is."),
        DistributionZone(code: "TRT", name: "Trinidad-Tobago"),
        DistributionZone(code: "VNA", name: "Venezuelan Antilles"),
        DistributionZone(code: "WIN", name: "Windward Is."),
        DistributionZone(code: "WIN-BA", name: "Barbados"),
        DistributionZone(code: "WIN-DO", name: "Dominica"),
        DistributionZone(code: "WIN-GR", name: "Grenada"),
        DistributionZone(code: "WIN-MA", name: "Martinique"),
        DistributionZone(code: "WIN-SL", name: "St. Lucia"),
        DistributionZone(code: "WIN-SV", name: "St. Vincent"),
        DistributionZone(code: "82", name: "Northern South America"),
        DistributionZone(code: "FRG", name: "French Guiana"),
        DistributionZone(code: "GUY", name: "Guyana"),
        DistributionZone(code: "SUR", name: "Suriname"),
        DistributionZone(code: "VEN", name: "Venezuela"),
        DistributionZone(code: "83", name: "Western South America"),
        DistributionZone(code: "BOL", name: "Bolivia"),
        DistributionZone(code: "CLM", name: "Colombia"),
        DistributionZone(code: "ECU", name: "Ecuador"),
        DistributionZone(code: "GAL", name: "Galápagos"),
        DistributionZone(code: "PER", name: "Peru"),
        DistributionZone(code: "84", name: "Brazil"),
        DistributionZone(code: "BZC", name: "Brazil West-Central"),
        DistributionZone(code: "BZC-DF", name: "Brasilia Distrito Federal"),
        DistributionZone(code: "BZC-GO", name: "Goias"),
        DistributionZone(code: "BZC-MS", name: "Mato Grosso do Sul"),
        DistributionZone(code: "BZC-MT", name: "Mato Grosso"),
        DistributionZone(code: "BZE", name: "Brazil Northeast"),
        DistributionZone(code: "BZE-AL", name: "Alagoas"),
        DistributionZone(code: "BZE-BA", name: "Bahia"),
        DistributionZone(code: "BZE-CE", name: "Ceara"),
        DistributionZone(code: "BZE-FN", name: "Fernando de Noronha"),
        DistributionZone(code: "BZE-MA", name: "Maranhao"),
        DistributionZone(code: "BZE-PB", name: "Paraiba"),
        DistributionZone(code: "BZE-PE", name: "Pernambuco"),
        DistributionZone(code: "BZE-PI", name: "Piaui"),
        DistributionZone(code: "BZE-RN", name: "Rio Grande do Norte"),
        DistributionZone(code: "BZE-SE", name: "Sergipe"),
        DistributionZone(code: "BZL", name: "Brazil Southeast"),
        DistributionZone(code: "BZL-ES", name: "Espirito Santo"),
        DistributionZone(code: "BZL-MG", name: "Minas Gerais"),
        DistributionZone(code: "BZL-RJ", name: "Rio de Janeiro"),
        DistributionZone(code: "BZL-SP", name: "Sao Paulo"),
        DistributionZone(code: "BZL-TR", name: "Trindade"),
        DistributionZone(code: "BZN", name: "Brazil North"),
        DistributionZone(code: "BZN-AC", name: "Acre"),
        DistributionZone(code: "BZN-AM", name: "Amazonas"),
        DistributionZone(code: "BZN-AP", name: "Amapa"),
        DistributionZone(code: "BZN-PA", name: "Para"),
        DistributionZone(code: "BZN-RM", name: "Roraima"),
        DistributionZone(code: "BZN-RO", name: "Rondonia"),
        DistributionZone(code: "BZN-TO", name: "Tocantins"),
        DistributionZone(code: "BZS", name: "Brazil South"),
        DistributionZone(code: "BZS-PR", name: "Parana"),
        DistributionZone(code: "BZS-RS", name: "Rio Grande do Sul"),
        DistributionZone(code: "BZS-SC", name: "Santa Catarina"),
        DistributionZone(code: "85", name: "Southern South America"),
        DistributionZone(code: "AGE", name: "Argentina Northeast"),
        DistributionZone(code: "AGE-BA", name: "Buenos Aires"),
        DistributionZone(code: "AGE-CD", name: "Cordoba"),
        DistributionZone(code: "AGE-CH", name: "Chaco"),
        DistributionZone(code: "AGE-CN", name: "Corrientes"),
        DistributionZone(code: "AGE-DF", name: "Argentina Distrito Federal"),
        DistributionZone(code: "AGE-ER", name: "Entre Rios"),
        DistributionZone(code: "AGE-FO", name: "Formosa"),
        DistributionZone(code: "AGE-LP", name: "La Pampa"),
        DistributionZone(code: "AGE-MI", name: "Misiones"),
        DistributionZone(code: "AGE-SF", name: "Santa Fe"),
        DistributionZone(code: "AGS", name: "Argentina South"),
        DistributionZone(code: "AGS-CB", name: "Chubut"),
        DistributionZone(code: "AGS-NE", name: "Neuquen"),
        DistributionZone(code: "AGS-RN", name: "Rio Negro"),
        DistributionZone(code: "AGS-SC", name: "Santa Cruz"),
        DistributionZone(code: "AGS-TF", name: "Tierra del Fuego (Argentina)"),
        DistributionZone(code: "AGW", name: "Argentina Northwest"),
        DistributionZone(code: "AGW-CA", name: "Catamarca"),
        DistributionZone(code: "AGW-JU", name: "Jujuy"),
        DistributionZone(code: "AGW-LR", name: "La Rioja"),
        DistributionZone(code: "AGW-ME", name: "Mendoza"),
        DistributionZone(code: "AGW-SA", name: "Salta"),
        DistributionZone(code: "AGW-SE", name: "Santiago del Estero"),
        DistributionZone(code: "AGW-SJ", name: "San Juan"),
        DistributionZone(code: "AGW-SL", name: "San Luis"),
        DistributionZone(code: "AGW-TU", name: "Tucuman"),
        DistributionZone(code: "CLC", name: "Chile Central"),
        DistributionZone(code: "CLC-BI", name: "Biobio"),
        DistributionZone(code: "CLC-CO", name: "Coquimbo"),
        DistributionZone(code: "CLC-LA", name: "La Araucania"),
        DistributionZone(code: "CLC-MA", name: "Maule"),
        DistributionZone(code: "CLC-OH", name: "O'Higgins"),
        DistributionZone(code: "CLC-SA", name: "Santiago"),
        DistributionZone(code: "CLC-VA", name: "Valparaiso"),
        DistributionZone(code: "CLN", name: "Chile North"),
        DistributionZone(code: "CLN-AN", name: "Antofagasta"),
        DistributionZone(code: "CLN-AT", name: "Atacama"),
        DistributionZone(code: "CLN-TA", name: "Tarapaca"),
        DistributionZone(code: "CLS", name: "Chile South"),
        DistributionZone(code: "CLS-AI", name: "Aisen"),
        DistributionZone(code: "CLS-LL", name: "Los Lagos"),
        DistributionZone(code: "CLS-MG", name: "Magellanes"),
        DistributionZone(code: "DSV", name: "Desventurados Is."),
        DistributionZone(code: "JNF", name: "Juan Fernández Is."),
        DistributionZone(code: "PAR", name: "Paraguay"),
        DistributionZone(code: "URU", name: "Uruguay"),
        DistributionZone(code: "9", name: "Antarctic"),
        DistributionZone(code: "90", name: "Subantarctic Islands"),
        DistributionZone(code: "ASP", name: "Amsterdam-St.Paul Is."),
        DistributionZone(code: "BOU", name: "Bouvet I."),
        DistributionZone(code: "CRZ", name: "Crozet Is."),
        DistributionZone(code: "FAL", name: "Falkland Is."),
        DistributionZone(code: "HMD", name: "Heard-McDonald Is."),
        DistributionZone(code: "KEG", name: "Kerguelen"),
        DistributionZone(code: "MAQ", name: "Macquarie Is."),
        DistributionZone(code: "MPE", name: "Marion-Prince Edward Is."),
        DistributionZone(code: "SGE", name: "South Georgia"),
        DistributionZone(code: "SSA", name: "South Sandwich Is."),
        DistributionZone(code: "TDC", name: "Tristan da Cunha"),
        DistributionZone(code: "91", name: "Antarctic Continent"),
        DistributionZone(code: "ANT", name: "Antarctica")
    ]
}
